### ISSUE TITLE
Passthrough for force control

### ISSUE THREAD

**Issue by ian-chuang** [UniversalRobots/Universal_Robots_ROS_passthrough_controllers#11]
It would be nice if there were pass through controllers in ROS for the UR e-series to move the robot using force control.

Currently, I am trying to do force control using this repo here: https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers

However, when I use the controller, I have some issues with the arm drifting and I feel it isn't too reliable. 

It would be really nice instead to be able to control the robot using ROS utilizing the existing force control program on the UR.

Perhaps one cartesian force controller that implements the motion command that takes in a wrench and another cartesian compliance controller that takes in a point

Would implementing something like this be difficult?

**Comment by urrsk** [comment]
@ian-chuang Agree and we are working on this. See the merged PR on the Client Library: https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/138

Though it is not yet added to ROS and ROS2 drivers
See https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/677 and https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/771

Close it here as I have addressed it in the driver repo
