### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by AlcatrAAz** [UniversalRobots/Universal_Robots_ROS_passthrough_controllers#8]
Hello

I want to use the passthrough controllers test function and the link "integration tests" in the Readme is broken under "Examples". It gives me an "404" error. A quick explanation how to use the test function would be also nice because the demo.launch doesn't exist anymore in this github repo.

Just to be sure: This is atm the passthrough controller that we should use?

Regards.

**Comment by stefanscherzinger** [comment]
Hi @AlcatrAAz 

Thanks for pointing this out. I'll fix that. The two test scripts that it should reference are [here](https://github.com/UniversalRobots/Universal_Robots_ROS_passthrough_controllers/blob/main/test/test_forward_cartesian_trajectory.py) and [here](https://github.com/UniversalRobots/Universal_Robots_ROS_passthrough_controllers/blob/main/test/test_forward_joint_trajectory.py).

> Just to be sure: This is atm the passthrough controller that we should use?

Yes, this is the right package for `pass_through_controllers`.
Until recent PRs are merged into the driver's mainline, a minimal setup could look like as described in [this post](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/390#issuecomment-872017473).

We are currently reworking the driver's `test_move` script.  The draft is [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/test_move/ur_robot_driver/scripts/test_move). You could have a look at that to find out how to use the different controller interfaces.
